const List<String> listCategories = [
  'Information Technology (IT)',
  'Engineering',
  'Marketing',
  'Sales',
  'Finance',
  'Human Resources (HR)',
  'Graphic Design',
  'UX/UI Design',
  'Flutter Developer',
  'Backend Developer',
  'Frontend Developer',
  'Full Stack Developer',
  'Mobile App Developer',
  'Software Engineer',
  'Data Scientist',
  'DevOps Engineer',
  'Machine Learning Engineer',
  'Data Engineer',
  'Game Developer',
  'Cloud Architect',

  
  'AI Engineer',
  'System Architect',
  'Blockchain Developer',
  'Embedded Systems Engineer',
  'Security Engineer',
  'QA Engineer',
  'Network Engineer',
  'Site Reliability Engineer (SRE)',
  'Big Data Engineer',
  'Database Administrator',
  'Automation Engineer',
  'API Developer',
  'iOS Developer',
  'Android Developer',
  'React Native Developer',
  'JavaScript Developer',
  'Python Developer',
  'Java Developer',
  'C++ Developer',
  'C# Developer',
  'PHP Developer',
  'Ruby Developer',
  'Kotlin Developer',
  'Go Developer',
  'Rust Developer',
  'Swift Developer',
  'Perl Developer',
  'Scala Developer',
  'R Developer',
  'TypeScript Developer',
  'SQL Developer',
  'NoSQL Developer',
  'Unity Developer',
  'Unreal Engine Developer',
  'AR/VR Developer',
  'DevSecOps Engineer',
  'Microservices Architect',
  'Web3 Developer',

  // Software Engineering categories
  'Agile Coach',
  'API Engineer',
  'Application Architect',
  'Application Developer',
  'Automation Tester',
  'Build and Release Engineer',
  'C# Engineer',
  'C++ Engineer',
  'Chief Technology Officer (CTO)',
  'Cloud Engineer',
  'Configuration Manager',
  'Continuous Integration Engineer',
  'CRM Developer',
  'Data Architect',
  'Data Migration Specialist',
  'Desktop Application Developer',
  'Digital Product Manager',
  'Director of Engineering',
  'Embedded Software Engineer',
  'Enterprise Architect',
  'Firmware Engineer',
  'Front-End Engineer',
  'Full Stack Software Engineer',
  'Game Engine Programmer',
  'Graphics Programmer',
  'Head of Engineering',
  'Integration Engineer',
  'iOS Software Engineer',
  'IT Manager',
  'IT Security Specialist',
  'Java Engineer',
  'Junior Software Engineer',
  'Lead Software Engineer',
  'Low-Level Programmer',
  'Machine Learning Researcher',
  'Mainframe Developer',
  'Microservices Developer',
  'Mobile Software Engineer',
  'Network Security Engineer',
  'Object-Oriented Programmer',
  'Open Source Developer',
  'Operations Engineer',
  'Platform Engineer',
  'Principal Software Engineer',
  'Product Engineer',
  'Release Manager',
  'Robotics Programmer',
  'SaaS Engineer',
  'Salesforce Developer',
  'SAP Developer',
  'Scrum Master',
  'Senior Software Developer',
  'Senior Software Engineer',
  'Software Architect',
  'Software Development Engineer',
  'Software Development Manager',
  'Software Quality Assurance Analyst',
  'Software Support Engineer',
  'Solutions Architect',
  'System Administrator',
  'System Engineer',
  'Technical Program Manager',
  'Technical Support Engineer',
  'Technical Writer',
  'Test Automation Engineer',
  'Test Engineer',
  'UI Engineer',
  'UX Engineer',
  'Video Game Developer',
  'Virtualization Engineer',
  'VoIP Engineer',
  'Web Architect',
  'Web Application Developer',
  'Web Security Engineer'

  'Healthcare',
  'Web Developer',
  'Education',
  'Customer Service',
  'Administration',
  'Accounting',
  'Design and Creative',
  'Legal',
  'Manufacturing',
  'Logistics and Supply Chain',
  'Hospitality',
  'Construction',
  'Real Estate',
  'Research and Development (R&D)',
  'Public Relations (PR)',
  'Consulting',
  'Project Management',
  'Operations',
  'Media and Communications',
  'Arts and Entertainment',
  'Non-Profit and Charity',
  'Retail',
  'Transportation',
  'Government and Public Sector',
  'Environmental Services',
  'Security and Protective Services',
  'Agriculture',
  'Food and Beverage',
  'Insurance',
  'Telecommunications',
  'Pharmaceuticals',
  'Aerospace and Defense',
  'Automotive',
  'Banking',
  'Biotechnology',
  'Chemicals',
  'Consumer Goods',
  'Energy and Utilities',
  'Fashion',
  'Mining and Metals',
  'Travel and Tourism',
  'Sports and Recreation',
  'Veterinary Services',
  'Translation and Interpretation',
  'Event Planning',
  'Video Production',
  'Publishing',
  'Architecture',
  'Cleaning and Maintenance',
  'Beauty and Wellness',
  'Fitness and Personal Training',
  'E-commerce',
  'Home Services',
  'Data Science and Analytics',
  'Supply Chain and Procurement',
  'Cybersecurity',
  'Game Development',
  'Hardware Development',
  'AI and Machine Learning',
  'Robotics',
  'Quantum Computing',
  'Sustainability and Green Energy',
  'Corporate Training',
  'Auditing',
  'Asset Management',
  'Private Equity',
  'Venture Capital',
  'Investment Banking',
  'Risk Management',
  'Actuarial Science',
  'Financial Planning',
  'Tax Advisory',
  'Market Research',
  'Social Media Management',
  'Search Engine Optimization (SEO)',
  'Content Writing',
  'Copywriting',

  'Video Editing',
  'Photography',
  'Film Production',
  'Interior Design',
  'Event Coordination',
  'Fundraising',
  'Speech Therapy',
  'Occupational Therapy',
  'Physical Therapy',
  'Nursing',
  'Emergency Medical Services (EMS)',
  'Dentistry',
  'Psychiatry',
  'Radiology',
  'Surgery',
  'Pathology',
  'Pharmacology',
  'Oncology',
  'Pediatrics',
  'Anesthesiology',
  'Neurology',
  'Dermatology',
  'Cardiology',
  'Clinical Research',
  'Public Health',
  'Epidemiology',
  'Speech Writing',
  'Public Policy',
  'International Relations',
  'Diplomacy',
  'Urban Planning',
  'Community Development',
  'Non-Governmental Organizations (NGOs)',
  'Library Science',
  'Museum Curation',
  'Archaeology',
  'History',
  'Anthropology',
  'Sociology',
  'Psychology',
  'Social Work',
  'Counseling',
  'Childcare',
  'Pet Care',
  'Animal Training',
  'Zoology',
  'Botany',
  'Forestry',
  'Horticulture',
  'Marine Biology',
  'Veterinary Medicine',
  'Wildlife Conservation',
  'Ecology',
  'Geology',
  'Meteorology',
  'Astronomy',
  'Physics',
  'Chemistry',
  'Biology',
  'Mathematics',
  'Statistics',
  'Economics',
  'Political Science',
  'Law Enforcement',
  'Firefighting',
  'Military',
  'Paramilitary',
  'Aviation',
  'Piloting',
  'Flight Attendant',
  'Air Traffic Control',
  'Maritime',
  'Shipping and Receiving',
  'Warehouse Management',
  'Customs and Border Control',
  'Freight and Logistics',
  'Driving',
  'Courier Services',
  'Mechanics',
  'Electronics Technician',
  'Plumbing',
  'Electrician',
  'Carpentry',
  'Masonry',
  'HVAC Technician',
  'Welding',
  'Fabrication',
  'Printing',
  'Packaging',
  'Quality Control',
  'Safety and Compliance',

];
